### PR TITLE
added profile pages java 

### PR DESCRIPTION
**Pull request by Bijay555**
I am making this PR as draft for necessary changes.
I have share a screenshot of it.
profile

### CODE REVIEW

**Comment by Bijay555** [comment]
fixes #7

**Comment by jyotijauhari** [comment]
@smaranjitghose , is this UI is okay with your plan?
 I think it matches with the description of the issue.

**Comment by jyotijauhari** [comment]
@Bijay555  send the pr . we will merge it for now.

**Comment by Bijay555** [comment]
@JyotiJauhari  you can merge

**Pull request merged**
