### PR TITLE
Added App code base

### PR DESCRIPTION
**Pull request by HaripriyaB**
### Description 
This commit adds the app's code base written in java language.

Fixes/Related to #4 

#### Note: I've used a temporary sample logo as a placeholder for splash screen.

Screen-Recording-20201020-143937

### CODE REVIEW

**Comment by jyotijauhari** [comment]
@HaripriyaB can you make splash screen little attractive?

**Comment by HaripriyaB** [comment]
> @HaripriyaB can you make splash screen little attractive?

@JyotiJauhari There is another issue regarding the splash screen design here #5 . So I think it's not relevant to this PR. Correct me if I'm wrong.

**Comment by jyotijauhari** [comment]
> > @HaripriyaB can you make splash screen little attractive?
> 
> @JyotiJauhari There is another issue regarding the splash screen design here #5 . So I think it's not relevant to this PR. Correct me if I'm wrong.

Oh okay  then @HaripriyaB.  💯

**Review by jyotijauhari — APPROVED** [review]

**Comment by jyotijauhari** [comment]
@smaranjitghose will merge your pr @HaripriyaB .

**Pull request merged**
